# Generated by Django 6.0.1 on 2026-02-25 14:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(default='REG-001', max_length=50)),
                ('print_immediately', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(default='Canine', max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.CharField(blank=True, max_length=20)),
                ('neutering_status', models.CharField(choices=[('No', 'No'), ('C', 'Castrated'), ('S', 'Spayed')], default='No', max_length=2)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_address', models.TextField(blank=True)),
                ('barangay', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DogRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=50)),
                ('name_of_pet', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('color_markings', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('status', models.CharField(choices=[('Castrated', 'Castrated'), ('Spayed', 'Spayed'), ('Intact', 'Intact')], max_length=20)),
                ('owner_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=20)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['section', 'number'],
            },
        ),
        migrations.CreateModel(
            name='PenaltySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DogAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='announcements/bg/')),
                ('background_color', models.CharField(default='#eeedf3', max_length=20)),
                ('schedule_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dogadoption_admin.dogannouncement')),
            ],
        ),
        migrations.CreateModel(
            name='DewormingTreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('medicine_given', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('veterinarian', models.CharField(max_length=255)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dewormings', to='dogadoption_admin.dogregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('penalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogadoption_admin.penalty')),
            ],
        ),
        migrations.AddField(
            model_name='penalty',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='dogadoption_admin.penaltysection'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('rescued', 'Rescued'), ('under_care', 'Under Care'), ('reunited', 'Reunited'), ('adopted', 'Adopted')], default='rescued', max_length=20)),
                ('rescued_date', models.DateField(default=django.utils.timezone.now)),
                ('claim_days', models.PositiveIntegerField(default=3, help_text='Days allowed for owner to claim dog')),
                ('violations', models.JSONField(blank=True, help_text='List of dog violations', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dogadoption_admin.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('claim', 'Claim'), ('adopt', 'Adopt')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='dogadoption_admin.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vaccine_name', models.CharField(max_length=255)),
                ('vaccine_expiry_date', models.DateField()),
                ('vaccination_expiry_date', models.DateField()),
                ('veterinarian', models.CharField(max_length=255)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='dogadoption_admin.dogregistration')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='penalty',
            unique_together={('section', 'number')},
        ),
    ]
