# Generated by Django 6.0.1 on 2026-02-03 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='claim_days',
            field=models.PositiveIntegerField(default=3, help_text='Days allowed for owner to claim dog'),
        ),
        migrations.AddField(
            model_name='post',
            name='rescued_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('rescued', 'Rescued'), ('under_care', 'Under Care'), ('reunited', 'Reunited'), ('adopted', 'Adopted')], default='rescued', max_length=20),
        ),
    ]
