# Generated by Django 6.0.1 on 2026-02-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0002_post_claim_days_post_rescued_date_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='violations',
            field=models.JSONField(blank=True, help_text='List of dog violations', null=True),
        ),
    ]
