# Generated by Django 6.0.1 on 2026-02-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0003_post_violations'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('post_type', models.CharField(choices=[('COLOR', 'Plain Color with Text'), ('IMAGE_BG', 'Image Background with Text'), ('PHOTO', 'Standard Photo Post')], default='COLOR', max_length=10)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='announcements/bg/')),
                ('background_color', models.CharField(default='#4f46e5', help_text='Hex code or Tailwind class', max_length=20)),
                ('schedule_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
