# Generated by Django 6.0.1 on 2026-02-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0007_announcementreaction_delete_announcementlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementcomment',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
