# Generated by Django 6.0.1 on 2026-02-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0009_postrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(default='Canine', max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.CharField(blank=True, max_length=20)),
                ('neutering_status', models.CharField(choices=[('No', 'No'), ('C', 'Castrated'), ('S', 'Spayed')], default='No', max_length=2)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_address', models.TextField(blank=True)),
            ],
        ),
    ]
