# Generated by Django 6.0.1 on 2026-02-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0010_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='barangay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
