# Generated by Django 6.0.1 on 2026-02-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0011_dog_barangay'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(default='REG-001', max_length=50)),
                ('print_immediately', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DogRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=50)),
                ('name_of_pet', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('color_markings', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('status', models.CharField(choices=[('Castrated', 'Castrated'), ('Spayed', 'Spayed'), ('Intact', 'Intact')], max_length=20)),
                ('owner_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=20)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
