# Generated by Django 6.0.1 on 2026-02-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0012_certificatesettings_dogregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogannouncement',
            name='background_color',
            field=models.CharField(default='#4f46e5', max_length=20),
        ),
        migrations.DeleteModel(
            name='AnnouncementReaction',
        ),
    ]
