# Generated by Django 6.0.1 on 2026-02-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0013_alter_dogannouncement_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogannouncement',
            name='post_type',
        ),
        migrations.AlterField(
            model_name='dogannouncement',
            name='background_color',
            field=models.CharField(default='#eeedf3', max_length=20),
        ),
    ]
