# Generated by Django 6.0.1 on 2026-03-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0013_alter_dogregistration_dob_optional'),
        ('dogadoption_admin', '0014_dogannouncementimage'),
    ]

    operations = [
    ]
