# Generated by Django 6.0.1 on 2026-02-24 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0014_remove_dogannouncement_post_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DewormingTreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('medicine_given', models.CharField(max_length=150)),
                ('route', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('veterinarian', models.CharField(max_length=150)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogadoption_admin.pet')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vaccine_name', models.CharField(max_length=100)),
                ('vaccine_expiry_date', models.DateField()),
                ('vaccination_expiry_date', models.DateField()),
                ('veterinarian', models.CharField(max_length=150)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogadoption_admin.pet')),
            ],
        ),
    ]
