# Generated by Django 6.0.1 on 2026-02-25 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0015_pet_dewormingtreatmentrecord_vaccinationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('dog_description', models.CharField(max_length=255)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('penalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogadoption_admin.penalty')),
            ],
        ),
    ]
