# Generated by Django 6.0.1 on 2026-03-04 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0015_merge_20260303_1502'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['is_read', 'created_at'], name='adminnotif_read_created_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementcomment',
            index=models.Index(fields=['announcement', 'created_at'], name='anncomment_ann_created_idx'),
        ),
        migrations.AddIndex(
            model_name='dogannouncement',
            index=models.Index(fields=['created_at'], name='dogann_created_idx'),
        ),
        migrations.AddIndex(
            model_name='dogannouncement',
            index=models.Index(fields=['category', 'created_at'], name='dogann_category_created_idx'),
        ),
        migrations.AddIndex(
            model_name='dogregistration',
            index=models.Index(fields=['date_registered'], name='dogreg_date_registered_idx'),
        ),
        migrations.AddIndex(
            model_name='globalappointmentdate',
            index=models.Index(fields=['is_active', 'appointment_date'], name='gappt_active_date_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='post_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'created_at'], name='post_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='postrequest',
            index=models.Index(fields=['post', 'request_type', 'status'], name='postreq_post_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='postrequest',
            index=models.Index(fields=['request_type', 'status', 'created_at'], name='postreq_type_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='postrequest',
            index=models.Index(fields=['user', 'request_type', 'status'], name='postreq_user_type_status_idx'),
        ),
    ]
