# Generated by Django 6.0.1 on 2026-02-25 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0016_penalty_citation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='penalty',
            options={'ordering': ['section', 'number']},
        ),
        migrations.AlterField(
            model_name='penalty',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='penalty',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='dogadoption_admin.penaltysection'),
        ),
        migrations.AlterUniqueTogether(
            name='penalty',
            unique_together={('section', 'number')},
        ),
    ]
