# Generated by Django 6.0.1 on 2026-03-05 00:00

import django.db.models.deletion
from django.db import migrations, models
import dogadoption_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ("dogadoption_admin", "0016_adminnotification_adminnotif_read_created_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DogImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to=dogadoption_admin.models.dog_registration_image_upload_to)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="dogadoption_admin.dog",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(fields=["dog", "created_at"], name="dogimg_dog_created_idx"),
                    models.Index(fields=["created_at"], name="dogimg_created_idx"),
                ],
            },
        ),
    ]
