# Generated by Django 6.0.1 on 2026-02-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0017_penaltysection_alter_penalty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='dogadoption_admin.penaltysection'),
        ),
    ]
