# Generated by Django 6.0.1 on 2026-03-05

import django.db.models.deletion
from django.db import migrations, models


def _normalize_person_name(value):
    return " ".join((value or "").split()).strip().casefold()


def _backfill_owner_identity(apps, schema_editor):
    Dog = apps.get_model("dogadoption_admin", "Dog")
    User = apps.get_model("auth", "User")

    users_by_owner_key = {}
    users = (
        User.objects.filter(is_staff=False)
        .exclude(first_name__isnull=True)
        .exclude(last_name__isnull=True)
        .order_by("id")
        .values("id", "first_name", "last_name")
    )
    for user in users:
        owner_key = _normalize_person_name(
            f"{user.get('first_name', '')} {user.get('last_name', '')}"
        )
        if owner_key and owner_key not in users_by_owner_key:
            users_by_owner_key[owner_key] = user["id"]

    updates = []
    for dog in Dog.objects.all().only("id", "owner_name").iterator(chunk_size=500):
        owner_key = _normalize_person_name(dog.owner_name)
        dog.owner_name_key = owner_key
        dog.owner_user_id = users_by_owner_key.get(owner_key)
        updates.append(dog)
        if len(updates) >= 500:
            Dog.objects.bulk_update(updates, ["owner_name_key", "owner_user"])
            updates = []

    if updates:
        Dog.objects.bulk_update(updates, ["owner_name_key", "owner_user"])


def _reset_owner_identity(apps, schema_editor):
    Dog = apps.get_model("dogadoption_admin", "Dog")
    Dog.objects.all().update(owner_name_key="", owner_user_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("dogadoption_admin", "0017_dogimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="owner_name_key",
            field=models.CharField(blank=True, db_index=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="dog",
            name="owner_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registered_dogs",
                to="auth.user",
            ),
        ),
        migrations.RunPython(_backfill_owner_identity, _reset_owner_identity),
    ]
