# Generated by Django 6.0.1 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogadoption_admin", "0018_dog_owner_identity_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dog",
            index=models.Index(fields=["date_registered"], name="dog_date_reg_idx"),
        ),
        migrations.AddIndex(
            model_name="dog",
            index=models.Index(fields=["barangay", "date_registered"], name="dog_brgy_date_idx"),
        ),
    ]
