# Generated by Django 6.0.1 on 2026-03-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogadoption_admin", "0019_dog_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnouncementReaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="dogadoption_admin.dogannouncement",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["announcement"], name="annreaction_announcement_idx"),
                    models.Index(fields=["user", "created_at"], name="annreaction_user_created_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("announcement", "user"),
                        name="annreaction_unique_user_per_announcement",
                    ),
                ],
            },
        ),
    ]
