# Generated by Django 5.0.2 on 2026-03-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0022_dewormingtreatmentrecord_medicine_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='owner_barangay',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='citation',
            name='owner_first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='citation',
            name='owner_last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('rescued', 'Rescued'), ('under_care', 'Under Care'), ('reunited', 'Reclaimed'), ('adopted', 'Adopted')], default='rescued', max_length=20),
        ),
    ]
