# Generated by Django 5.0.2 on 2026-03-30 14:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0028_registration_hotspot_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserViolationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_violation_count', models.PositiveIntegerField(default=3)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('letter_status', models.CharField(choices=[('generated', 'Generated'), ('printed', 'Printed')], default='generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_violation_notification', to='dogadoption_admin.adminnotification')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserViolationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dogadoption_admin.userviolationnotification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='violation_summary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserViolationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=160)),
                ('details', models.TextField(blank=True)),
                ('recorded_on', models.DateField(default=django.utils.timezone.localdate)),
                ('violation_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_violation_entries', to=settings.AUTH_USER_MODEL)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dogadoption_admin.userviolationsummary')),
            ],
            options={
                'ordering': ['-violation_number', '-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='userviolationnotification',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dogadoption_admin.userviolationsummary'),
        ),
        migrations.AddIndex(
            model_name='userviolationsummary',
            index=models.Index(fields=['violation_count', 'updated_at'], name='usrviolsum_count_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='userviolationrecord',
            index=models.Index(fields=['summary', 'violation_number'], name='usrviolrec_sum_num_idx'),
        ),
        migrations.AddIndex(
            model_name='userviolationrecord',
            index=models.Index(fields=['recorded_on', 'created_at'], name='usrviolrec_date_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='userviolationnotification',
            index=models.Index(fields=['letter_status', 'created_at'], name='usrviolnotif_status_cr_idx'),
        ),
        migrations.AddConstraint(
            model_name='userviolationnotification',
            constraint=models.UniqueConstraint(fields=('summary', 'trigger_violation_count'), name='usrviolnotif_unique_sum_count'),
        ),
    ]
