# Generated by Django 5.0.2 on 2026-03-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0029_userviolationnotification_userviolationsummary_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserViolationRecord',
        ),
    ]
