# Generated by Django 5.0.2 on 2026-04-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0034_post_is_pinned_post_pinned_at_alter_post_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='breed',
            field=models.CharField(blank=True, choices=[('aspin', 'Aspin / Mixed Local Breed'), ('american_bully', 'American Bully'), ('american_staffordshire_terrier', 'American Staffordshire Terrier'), ('beagle', 'Beagle'), ('belgian_malinois', 'Belgian Malinois'), ('border_collie', 'Border Collie'), ('boxer', 'Boxer'), ('bull_terrier', 'Bull Terrier'), ('chihuahua', 'Chihuahua'), ('chow_chow', 'Chow Chow'), ('cocker_spaniel', 'Cocker Spaniel'), ('corgi', 'Corgi'), ('dalmatian', 'Dalmatian'), ('dachshund', 'Dachshund'), ('doberman', 'Doberman Pinscher'), ('french_bulldog', 'French Bulldog'), ('german_shepherd', 'German Shepherd'), ('golden_retriever', 'Golden Retriever'), ('great_dane', 'Great Dane'), ('husky', 'Siberian Husky'), ('jack_russell_terrier', 'Jack Russell Terrier'), ('japanese_spitz', 'Japanese Spitz'), ('labrador', 'Labrador Retriever'), ('maltese', 'Maltese'), ('miniature_pinscher', 'Miniature Pinscher'), ('pit_bull', 'Pit Bull'), ('pomeranian', 'Pomeranian'), ('poodle', 'Poodle'), ('pug', 'Pug'), ('rottweiler', 'Rottweiler'), ('samoyed', 'Samoyed'), ('schnauzer', 'Schnauzer'), ('shih_tzu', 'Shih Tzu'), ('yorkshire_terrier', 'Yorkshire Terrier'), ('other', 'Other')], default='', max_length=40),
        ),
    ]
