# Generated by Django 5.0.2 on 2026-04-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0035_alter_post_breed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dogregistration',
            index=models.Index(fields=['reg_no'], name='dogreg_reg_no_idx'),
        ),
    ]
