# Generated by Django 5.0.2 on 2026-04-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0037_citation_penalty_subitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrequest',
            name='anti_rabies_proof',
            field=models.ImageField(blank=True, null=True, upload_to='adoption_docs/anti_rabies/'),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='vaccination_history',
            field=models.ImageField(blank=True, null=True, upload_to='adoption_docs/vaccines/'),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='valid_id',
            field=models.ImageField(blank=True, null=True, upload_to='adoption_docs/ids/'),
        ),
    ]
