# Generated by Django 6.0.1 on 2026-04-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0038_postrequest_anti_rabies_proof_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'POST IMAGES'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='admin_dog_post',
        ),
        migrations.AlterModelTable(
            name='postimage',
            table='PostImages',
        ),
    ]
