# Generated by Django 6.0.1 on 2026-04-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0039_alter_postimage_options_alter_post_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminnotification',
            table='dogadoption_admin_notification',
        ),
        migrations.AlterModelTable(
            name='certificatesettings',
            table='dogadoption_admin_certificate',
        ),
        migrations.AlterModelTable(
            name='citation',
            table='dogadoption_admin_citation',
        ),
        migrations.AlterModelTable(
            name='dewormingtreatmentrecord',
            table='dogadoption_admin_dewormingtreatmentrecord',
        ),
        migrations.AlterModelTable(
            name='dog',
            table='dogadoption_admin_registerdog',
        ),
        migrations.AlterModelTable(
            name='dogannouncement',
            table='dogadoption_admin_postannouncement',
        ),
        migrations.AlterModelTable(
            name='dogannouncementimage',
            table='dogadoption_admin_dogannouncementimage',
        ),
        migrations.AlterModelTable(
            name='dogregistration',
            table='dogadoption_admin_vaccinationcertificate',
        ),
        migrations.AlterModelTable(
            name='globalappointmentdate',
            table='dogadoption_admin_globalappointmentdate',
        ),
        migrations.AlterModelTable(
            name='penalty',
            table='dogadoption_admin_penalty',
        ),
        migrations.AlterModelTable(
            name='pet',
            table='dogadoption_admin_petchoice',
        ),
        migrations.AlterModelTable(
            name='post',
            table='dogadoption_admin_dogpost',
        ),
        migrations.AlterModelTable(
            name='postimage',
            table='dogadoption_admin_postimages',
        ),
        migrations.AlterModelTable(
            name='staffaccess',
            table='dogadoption_admin_staffaccess',
        ),
        migrations.AlterModelTable(
            name='userviolationsummary',
            table='dogadoption_admin_userviolationsummary',
        ),
        migrations.AlterModelTable(
            name='vaccinationrecord',
            table='dogadoption_admin_vaccinationrecord',
        ),
    ]
