# Generated by Django 5.0.2 on 2026-04-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0041_vetadminprofile_username_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vetadminprofile',
            options={'verbose_name': 'Vet admin profile', 'verbose_name_plural': 'Vet admin profiles'},
        ),
    ]
