# Generated by Django 5.1.4 on 2026-04-25 07:06

import django.db.models.deletion
from django.db import migrations, models


def _backfill_completed_surrender_records(apps, schema_editor):
    DogCaptureRequest = apps.get_model("user", "DogCaptureRequest")
    CompletedSurrenderRecord = apps.get_model("dogadoption_admin", "CompletedSurrenderRecord")
    for cr in DogCaptureRequest.objects.filter(status="captured", request_type="surrender").iterator(chunk_size=500):
        CompletedSurrenderRecord.objects.get_or_create(capture_request_id=cr.pk, defaults={})


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0042_alter_vetadminprofile_options'),
        ('user', '0027_dog_surrender_request_gender_color_rename_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedSurrenderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_notes', models.TextField(blank=True, default='')),
                ('voided_at', models.DateTimeField(blank=True, help_text='When set, this row is hidden from the completed-surrender register.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capture_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_completed_surrender_record', to='user.dogcapturerequest')),
            ],
            options={
                'verbose_name': 'Completed surrender record',
                'verbose_name_plural': 'Completed surrender records',
                'db_table': 'dogadoptionadmin_completedsurrenderrecords',
                'ordering': ('-capture_request__captured_at', '-id'),
            },
        ),
        migrations.RunPython(_backfill_completed_surrender_records, _noop_reverse),
    ]
