# Generated by Django 5.1.4 on 2026-04-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0043_completedsurrenderrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedSurrenderRecord',
        ),
    ]
