# Generated by Django 5.1.4 on 2026-04-25 07:28

import django.db.models.deletion
from django.db import migrations, models


def forwards_backfill_dog_surrender_records(apps, schema_editor):
    DogCaptureRequest = apps.get_model('user', 'DogCaptureRequest')
    DogSurrenderRecord = apps.get_model('dogadoption_admin', 'DogSurrenderRecord')
    qs = DogCaptureRequest.objects.filter(status='captured', request_type='surrender')
    for req in qs.iterator():
        DogSurrenderRecord.objects.get_or_create(capture_request=req, defaults={})


def backwards_clear_dog_surrender_records(apps, schema_editor):
    DogSurrenderRecord = apps.get_model('dogadoption_admin', 'DogSurrenderRecord')
    DogSurrenderRecord.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0044_remove_completedsurrenderrecord'),
        ('user', '0027_dog_surrender_request_gender_color_rename_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogSurrenderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_notes', models.TextField(blank=True, default='')),
                ('voided_at', models.DateTimeField(blank=True, help_text='When set, hidden from the admin surrender register list.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capture_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_dog_surrender_record', to='user.dogcapturerequest')),
            ],
            options={
                'verbose_name': 'Dog surrender record',
                'verbose_name_plural': 'Dog surrender records',
                'db_table': 'dogadoptionadmin_dogsurrender_record',
                'ordering': ('-capture_request__captured_at', '-id'),
            },
        ),
        migrations.RunPython(forwards_backfill_dog_surrender_records, backwards_clear_dog_surrender_records),
    ]
