# Generated by Django 5.1.4 on 2026-04-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0045_dogsurrenderrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogsurrenderrecord',
            name='voided_at',
            field=models.DateTimeField(blank=True, help_text='When set, hidden from the admin dog surrender records list.', null=True),
        ),
    ]
