# Generated by Django 5.1.4 on 2026-04-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0046_alter_dogsurrenderrecord_voided_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dogsurrenderrecord',
            table='surrenderdogs',
        ),
    ]
