# Generated by Django 6.0.4 on 2026-04-27 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0048_remove_announcement_campaign_bucket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeceasedDog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=200)),
                ('breed', models.CharField(blank=True, default='', max_length=200)),
                ('deceased_at', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deceased_dog_entries', to='dogadoption_admin.post')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deceased_dog_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deceased dog',
                'verbose_name_plural': 'Deceased dogs',
                'db_table': 'dogadoptionadmin_deceased_dogs',
                'ordering': ('-deceased_at', '-id'),
                'indexes': [models.Index(fields=['deceased_at'], name='deceaseddogs_deceased_at_idx')],
            },
        ),
    ]
