# Generated by Django 6.0.4 on 2026-04-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0049_deceased_dogs'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dogregistration',
            index=models.Index(fields=['status'], name='dogreg_status_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccinationrecord',
            index=models.Index(fields=['date'], name='vacrec_vaccination_date_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccinationrecord',
            index=models.Index(fields=['registration_id'], name='vacrec_patient_id_idx'),
        ),
    ]
