# Generated by Django 6.0.4 on 2026-04-28 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0050_vaccination_list_print_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deceaseddog',
            name='age_group',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='deceaseddog',
            name='caption_excerpt',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='deceaseddog',
            name='coat_length',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='deceaseddog',
            name='colors_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deceaseddog',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='deceaseddog',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deceaseddog',
            name='post_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deceaseddog',
            name='post_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='deceaseddog',
            name='rescued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deceaseddog',
            name='size_group',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='deceaseddog',
            index=models.Index(fields=['dog_name'], name='deceaseddogs_dog_name_idx'),
        ),
        migrations.AddIndex(
            model_name='deceaseddog',
            index=models.Index(fields=['post'], name='deceaseddogs_post_id_idx'),
        ),
        migrations.AlterModelTable(
            name='deceaseddog',
            table='dogadoption_admin_deceaseddogs',
        ),
    ]
