# Generated by Django 6.0.4 on 2026-04-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0051_deceased_dogs_registry_table_and_snapshot_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='pet_photo_opt',
            field=models.ImageField(blank=True, help_text='JPEG derivative (quality 85); original image field is unchanged.', null=True, upload_to='post_images/opt/'),
        ),
    ]
