# Generated by Django 6.0.4 on 2026-05-12 11:39

import django.db.models.deletion
import dogadoption_admin.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0052_image_optimizer_derivatives'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to=dogadoption_admin.models.vaccination_card_pdf_upload_to)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_cards_created', to=settings.AUTH_USER_MODEL)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_cards', to='dogadoption_admin.dog')),
            ],
            options={
                'db_table': 'dogadoption_admin_vaccinationcard',
                'ordering': ['-id'],
            },
        ),
    ]
