# Generated by Django 4.2.7 on 2026-03-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_dogcapturerequestlandmarkimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogcapturerequest',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dogcapturerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('captured', 'Captured'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
