# Generated by Django 6.0.1 on 2026-02-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_ownerclaim_claimimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile_images/default-user-image.jpg', upload_to='profile_images/'),
        ),
    ]
