# Generated by Django 6.0.1 on 2026-03-04 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_dogcapturerequest_captured_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dogcapturerequest',
            index=models.Index(fields=['status', 'created_at'], name='dogcap_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='dogcapturerequest',
            index=models.Index(fields=['requested_by', 'status', 'created_at'], name='dogcap_user_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='dogcapturerequest',
            index=models.Index(fields=['assigned_admin', 'status'], name='dogcap_admin_status_idx'),
        ),
        migrations.AddIndex(
            model_name='missingdogpost',
            index=models.Index(fields=['status', 'created_at'], name='missingdog_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='missingdogpost',
            index=models.Index(fields=['owner', 'status'], name='missingdog_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='useradoptionpost',
            index=models.Index(fields=['status', 'created_at'], name='uadoptpost_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='useradoptionpost',
            index=models.Index(fields=['owner', 'status'], name='uadoptpost_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='useradoptionrequest',
            index=models.Index(fields=['post', 'status'], name='uadoptreq_post_status_idx'),
        ),
        migrations.AddIndex(
            model_name='useradoptionrequest',
            index=models.Index(fields=['requester', 'status'], name='uadoptreq_req_status_idx'),
        ),
    ]
