# Generated by Django 6.0.1 on 2026-02-10 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadoption_admin', '0009_postrequest'),
        ('user', '0007_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimimage',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dogadoption_admin.postrequest'),
        ),
        migrations.AlterField(
            model_name='claimimage',
            name='image',
            field=models.ImageField(upload_to='claim_images/'),
        ),
    ]
