# Generated by Django 6.0.1 on 2026-02-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_claimimage_claim_alter_claimimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogcapturerequest',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dogcapturerequest',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
