# Generated by Django 5.0.2 on 2026-03-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_dogcapturerequest_dogcap_status_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingdogpost',
            name='contact_facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='missingdogpost',
            name='contact_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
