# Generated by Django 5.0.2 on 2026-03-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_missingdogpost_contact_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradoptionpost',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=10),
        ),
    ]
