# Generated by Django 5.0.2 on 2026-03-16 02:26

from django.db import migrations, models


def populate_existing_capture_submission_types(apps, schema_editor):
    DogCaptureRequest = apps.get_model('user', 'DogCaptureRequest')
    DogCaptureRequest.objects.filter(submission_type__isnull=True).update(submission_type='online')


def reset_existing_capture_submission_types(apps, schema_editor):
    DogCaptureRequest = apps.get_model('user', 'DogCaptureRequest')
    DogCaptureRequest.objects.filter(submission_type='online').update(submission_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_useradoptionpost_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogcapturerequest',
            name='preferred_appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dogcapturerequest',
            name='request_type',
            field=models.CharField(choices=[('capture', 'Request Dog Capture'), ('surrender', 'Request Dog Surrender')], default='capture', max_length=20),
        ),
        migrations.AddField(
            model_name='dogcapturerequest',
            name='submission_type',
            field=models.CharField(blank=True, choices=[('walk_in', 'Walk-in Request (Office)'), ('online', 'Online Request')], max_length=20, null=True),
        ),
        migrations.RunPython(
            populate_existing_capture_submission_types,
            reset_existing_capture_submission_types,
        ),
    ]
