# Generated by Django 5.0.2 on 2026-04-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_profile_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogcapturerequest',
            name='request_type',
            field=models.CharField(choices=[('capture', 'Request Dog Capture'), ('surrender', 'Request Dog Surrender')], default='surrender', max_length=20),
        ),
        migrations.AlterField(
            model_name='dogcapturerequest',
            name='submission_type',
            field=models.CharField(blank=True, choices=[('walk_in', 'Walk-in Request (Office)'), ('online', 'Online Request')], default='online', max_length=20, null=True),
        ),
    ]
