# Generated by Django 5.0.2 on 2026-04-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_useradoptionpost_age_group_useradoptionpost_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingdogpost',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('missing', 'Missing'), ('found', 'Found'), ('declined', 'Declined')], default='pending_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='useradoptionpost',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('available', 'Available'), ('adopted', 'Adopted'), ('declined', 'Declined')], default='pending_review', max_length=20),
        ),
    ]
