# Generated by Django 5.0.2 on 2026-04-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_missingdogpost_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_read_keys',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
