# Generated by Django 5.0.2 on 2026-04-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_profile_notification_read_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradoptionrequest',
            name='anti_rabies_proof',
            field=models.ImageField(blank=True, null=True, upload_to='adoption_docs/anti_rabies/'),
        ),
        migrations.AddField(
            model_name='useradoptionrequest',
            name='vaccination_history',
            field=models.ImageField(blank=True, null=True, upload_to='adoption_docs/vaccines/'),
        ),
        migrations.AddField(
            model_name='useradoptionrequest',
            name='valid_id',
            field=models.ImageField(blank=True, null=True, upload_to='adoption_docs/ids/'),
        ),
    ]
