# Generated by Django 5.0.2 on 2026-04-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_useradoptionrequest_anti_rabies_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradoptionpost',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useradoptionpost',
            name='is_vaccinated',
            field=models.BooleanField(default=False),
        ),
    ]
