# Generated by Django 5.0.2 on 2026-04-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_add_dogsighting_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified_sightings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
