# Generated by Django 5.0.2 on 2026-04-23 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_add_verified_sightings_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingdogpost',
            name='reward',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='MissingDogPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='missing_dogs/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='user.missingdogpost')),
            ],
            options={
                'indexes': [models.Index(fields=['post'], name='missingdog_photo_post_idx')],
            },
        ),
    ]
