# Generated by Django 6.0.1 on 2026-04-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_missingdogpost_reward_missingdogphoto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='missingdogpost',
            table='user_missingdogpost',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='User_Profile',
        ),
        migrations.AlterModelTable(
            name='useradoptionpost',
            table='user_adoptionpost',
        ),
    ]
