# Generated by Django 5.0.2 on 2026-04-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_missingdogpost_table_alter_profile_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogcapturerequest',
            name='color_other',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dogcapturerequest',
            name='colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dogcapturerequest',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=10),
        ),
        migrations.AlterModelTable(
            name='dogcapturerequest',
            table='user_dogsurrender_request',
        ),
    ]
