# Generated by Django 5.1.4 on 2026-04-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_dog_surrender_request_gender_color_rename_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogcapturerequest',
            name='dog_age_group',
            field=models.CharField(blank=True, choices=[('puppy', 'Puppy (< 1 year)'), ('young', 'Young (1-3 years)'), ('adult', 'Adult (3-8 years)'), ('senior', 'Senior (8+ years)')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dogcapturerequest',
            name='dog_age_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dogcapturerequest',
            name='dog_breed',
            field=models.CharField(blank=True, choices=[('aspin', 'Aspin / Mixed Local Breed'), ('american_bully', 'American Bully'), ('american_staffordshire_terrier', 'American Staffordshire Terrier'), ('beagle', 'Beagle'), ('belgian_malinois', 'Belgian Malinois'), ('border_collie', 'Border Collie'), ('boxer', 'Boxer'), ('bull_terrier', 'Bull Terrier'), ('chihuahua', 'Chihuahua'), ('chow_chow', 'Chow Chow'), ('cocker_spaniel', 'Cocker Spaniel'), ('corgi', 'Corgi'), ('dalmatian', 'Dalmatian'), ('dachshund', 'Dachshund'), ('doberman', 'Doberman Pinscher'), ('french_bulldog', 'French Bulldog'), ('german_shepherd', 'German Shepherd'), ('golden_retriever', 'Golden Retriever'), ('great_dane', 'Great Dane'), ('husky', 'Siberian Husky'), ('jack_russell_terrier', 'Jack Russell Terrier'), ('japanese_spitz', 'Japanese Spitz'), ('labrador', 'Labrador Retriever'), ('maltese', 'Maltese'), ('miniature_pinscher', 'Miniature Pinscher'), ('pit_bull', 'Pit Bull'), ('pomeranian', 'Pomeranian'), ('poodle', 'Poodle'), ('pug', 'Pug'), ('rottweiler', 'Rottweiler'), ('samoyed', 'Samoyed'), ('schnauzer', 'Schnauzer'), ('shih_tzu', 'Shih Tzu'), ('yorkshire_terrier', 'Yorkshire Terrier'), ('other', 'Other')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='dogcapturerequest',
            name='dog_breed_other',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
