# Generated by Django 6.0.4 on 2026-04-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_dog_surrender_breed_age_and_surrenderdogs_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradoptionrequest',
            name='cert_opt',
            field=models.ImageField(blank=True, help_text='JPEG derivative of vaccination scan (quality 95); original uploads unchanged.', null=True, upload_to='adoption_docs/vaccines/opt/'),
        ),
    ]
